configs/am62xx-lp-evm.cpp, utils/perf_stats.cpp
The AM62x has a DDR4 and the AM62x-LP has a LPDDR4. The DDR_BURST_SIZE is different for both (16 and 32 respectively). So to differentiate these two, create a separate config for AM62x-LP and update the perf_stats.cpp accordingly.
=> AM62x Family: Fix DDR bandwidth calculations

apps/stats.qml, backend/includes/stats.h, backend/stats.cpp
The thermal nodes /sys/class/thermal/thermal_zone*/temp allows us to read temperature of different thermal_zones within the SoC. Since all the thermal_zones will be at similar temperatures, only read the thermal_zone0 because it is common for all SoCs.
Display the value in the stats window as a gradient (Green, Yellow, Red).
If thermal_zones are not available, the value displayed will be 0 C.
=> Stats: Read and Display SoC temperature from thermal nodes

configs/am62pxx-evm.cpp, configs/am62xx-lp-evm.cpp, configs/am62xx-sip-evm.cpp
- AM62x-SIP is a strip down version of AM62x platform with 512 Mb RAM. So most of the applications available won't work on this. So create a minimal config with only what will be functional. We also have to create a minimal industrial hmi application which is less intensive on memory.
- AM62P is another platform with a new and powerful SoC. The device bringup is still in progress so not all features are supported. So use a minimal config and enable applications as and when the baseport supports it.
=> Add initial support for AM62x-SIP and AM62Px platforms

configs/am62xxsip-evm.cpp
- The Yocto machine for AM62x SIP is am62xxsip-evm. Hence, rename the config and update the platform.
=> AM62 SIP: Update and rename am62xx-sip-evm.cpp to am62xxsip-evm.cpp

configs/am62xxsip-evm.cpp
- Seva Store via ti-apps-launcher isn't planned for AM62SIP. Hence, remove the browser load function needed for seva-browser.
=> configs: am62xxsip-evm: Remove Docker Load

backend/arm_analytics.cpp
The compilation would fail for all SOCs for which the ifdefs do not cover the variable definitions. Add default empty strings as quick fix
=> ARM Analytics: Add dummy pipelines to fix compilation errors

backend/live_camera.cpp, configs/am62pxx-evm.cpp, configs/am62xx-evm.cpp, configs/am62xx-lp-evm.cpp, configs/am62xxsip-evm.cpp
This reverts [96fb029](https://github.com/TexasInstruments/ti-apps-launcher/commit/96fb02984c260300d50d94c4bc66e122b7b3903f) while also adding Camera app support to the new AM62P platform.
=> Sitara Platforms: Add back live camera app

backend/settings.cpp, backend/stats.cpp
Using sudo every second to get gpu load and soc temperature is causing journalctl to be flooded with sudo logs. Also, using sudo is not needed because the ti-apps-launcher itself is run as root user. So remove sudo.
=> remove usage of sudo

configs/am62pxx-evm.cpp, configs/am62xx-evm.cpp, configs/am62xx-lp-evm.cpp, configs/am68-sk.cpp, configs/am69-sk.cpp
- With GPU accelerated Chromium Browser integrated in SDK 9.2 release [1], seva-launcher-aarch64 will be responsible to create a localhost page on port 8000 [2].
- Hence, update seva-store command for all platforms to launch Chromium Browser with http://localhost:8000/#/ once user clicks Seva Store on ti-apps-launcher.
[1]: https://git.ti.com/cgit/arago-project/meta-arago/commit/?h=kirkstone&id=1c7e65c70d3d0648274b9945a94dc8a3b69e5b94
[2]: https://git.ti.com/cgit/ti-sdk-linux/meta-tisdk/commit/?h=kirkstone&id=0b32034480906ea67f5a7ef80b01590abedd89f6
=> configs: Update Seva Store Command for all platforms

backend/camera.cpp
These platforms do not have ticolorconvert gst plugin available in the default filesystem. Hence use the videoconvert option for the recorder gstreamer pipeline.
=> camera app: s/ticolorconvert/videoconvert for AM67/AM68/AM69

configs/am62pxx-evm.cpp, configs/am62xx-evm.cpp, configs/am62xx-lp-evm.cpp, configs/beagleplay.cpp
- For SDK 10.0, Chromium has be upgraded to v123 [1]. With Chromium v123 it's observed that it auto launches a "Welcome to Chrome" tab on it's first run.
- To prevent it, use --no-first-run flag while launching Chromium to ensure a smoother OOB experience of Seva Store & WebGL Aquarium Demo.
[1]: https://git.ti.com/cgit/arago-project/meta-arago/commit/?h=scarthgap&id=2ac8e1bc67f9562a2670d2accf23d01c4508509f
=> configs: Modify RunCmd for seva_store & chromium_browser for SITARA

apps/wifi.qml, configs/am62pxx-evm.cpp
Add wifi demo application for AM62Pxx EVM.
Features:
- Connect to wifi using ssid, password, pmf.
- Connect to enterprise account supported.
- Different security type NONE, WPA-PSK, SAE, WPA-EAP, WPA-EAP-SHA256.
=> am62pxx-evm.cpp: Add wifi demo for AM62pxx

apps/wifi.qml, backend/includes/wifi.h, backend/wifi.cpp
Remove previousWifiOn property from QML and add it to backend. The backend implementation ensures that previousWifiOn persists across apps and does not reset when switching apps or demos. Also implement getter functions amd change notifications for previousWifiOn in the backend.
=> wifi: Add previousWifiOn property to track Wifi state changes

scripts/setup_cameras.sh
Update the path in setup_camera.sh script to detect the correct number of USB cameras connected to the device
=> scripts:setup_camera.sh: Update the script to show the correct count of USB cameras detected

configs/am62pxx-evm.cpp, configs/am62xx-evm.cpp, configs/am62xx-lp-evm.cpp
Low power mode is not supported on RT Linux. So drop suspend button from ti-apps-launcher for RT Linux image build. To achieve this add a new RT_BUILD flag which when enabled does not includes the suspend button during qmake. After this change, ti-apps-launcher for RT Linux build should be build with RT_BUILD=1.
Also add suspend button for am62lp config.
=> Remove suspend button for RT linux build

apps/3d_demo.qml, apps/appsmenu.qml, apps/arm_analytics.qml, apps/auto_cluster.qml, apps/benchmarks.qml, apps/benchmarks_jacinto.qml, apps/camera.qml, apps/chromium_browser.qml, apps/codecs.qml, apps/deviceinfo.qml, apps/gpu_performance.qml, apps/industrial_control.qml, apps/industrial_control_minimal.qml, apps/industrial_control_sitara.qml, apps/live_camera.qml, apps/settings.qml, apps/seva_store.qml, apps/stats.qml, apps/topbar.qml, apps/wifi.qml, ti-apps-launcher.qml
Like header files in C, we should only import what we need in QML. Several of these unneeded imported modules are no longer available in Qt6, so this helps with the migration.
=> Remove unneeded QML module imports

CMakeLists.txt, apps/appsmenu.qml, apps/arm_analytics.qml, apps/auto_cluster.qml, apps/camera.qml, apps/codecs.qml, apps/industrial_control.qml, apps/industrial_control_minimal.qml, apps/industrial_control_sitara.qml, apps/live_camera.qml, apps/terminal.qml, backend/appsmenu.cpp
Switch default build target to Qt6. Some sub-components are still not functional such as GStreamer based ones and the control demos.
=> Initial Qt6 migration

apps/live_camera.qml, backend/includes/live_camera.h, backend/live_camera.cpp, configs/am62pxx-evm.h, configs/am62xx-evm.h, configs/am62xx-lp-evm.h
This PR migrates live_camera demo to Qt6 and qml6glsink.
Originally (before 11.0), we had a different camera demo for AM62P. But that demo will be migrated in a different PR, so until then, lets have live_camera as a placeholder in AM62P too.
This PR has been tested on SK-AM62B.
=> Migrate live_camera to Qt6 and qml6glsink

configs/am67-sk.h, configs/am68-sk.h, configs/am69-sk.h
As part of QT6 migration, sync the Jacinto platforms with the rest... This includes some proper fixes like updating the proper dtmatch string for AM68-SK and switching to the app_industrial_control_sitara and the app_live_camera app which are the working versions of the apps. The original versions of these have not been migrated to QT6 yet.
=> configs: am6[789]-sk.h: Sync platform configs with the rest

apps/CircularGauge.qml, apps/auto_cluster.qml
Display cluster UI looks pretty bad at the moment. So this PR improves it. 
With this PR, the auto_cluster UI goes back to being very similar to how it used to be in 10.1 release.
An exception is the RadialGradient, which is still commented out. When run with qmlscene on PC, RadialGradient works fine. But when run on board with OLDI display, it casts a black shadow from the top-left of the screen to the bottom center.
As a result, it continues to be commented out. So the blue shade on the corners of the screen aren't there.
=> Improve auto_cluster UI
